install skat.core to /usr/lib
before it wouldn't have been found in /usr/bin anyway, so every
possible path is now checked manually in the start script

diff --git a/skat-host b/skat-host
--- a/skat-host
+++ b/skat-host
@@ -1,3 +1,13 @@
 #!/bin/sh
 
-sbcl --noinform --core skat.core --no-userinit --eval "(progn (kern::start-host-xmpp-toplevel) (quit))" $@
+for core in /usr/lib/skat.core /usr/local/lib/skat.core skat.core;
+do
+    if [ -e $core ]; then
+	sbcl --noinform --core $core --no-userinit --eval "(progn (kern::start-host-xmpp-toplevel) (quit))" $@
+	exit 0
+    fi
+done
+
+# no core found?
+echo "Fatal error: cannot find skat.core!"
+exit 1
